### ISSUE TITLE
removing background

### ISSUE THREAD

**Issue by EveTC** [cran/colordistance#1]
Hello,

Firstly thanks for the package, it looks like it will be really useful!
I have had a play on some text images, example below:
![EN19M18_D_calibrated](https://user-images.githubusercontent.com/38794463/60981920-23261700-a32f-11e9-969c-9bffa59dedaf.jpg)

As you can see some my background is not white (after claibration) and some of the colours are close to the background (other wings are ligter and are even more similar to the background), which means that it hard to remove these pixels using the lower and upper in the plotpixels() function. Well on my test run it seems to change the plot but does not remove the background colour as far as I can see (it isnt obvious that it is doing anything )).

To get around this I was looking at your flounder example and its seems that you outline the fish and delete the background? Was this done manually? I will have over 2000 images to analyse like the above and am hoping there is a way to automate this step?

I look forward to hearing from you.
Thanks,
Eve

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file.

**Comment by EveTC** [comment]
my appologies! Thank you for pointing this out.
